package JavaBasics;

public class For_Loop_If_Else {

	public static void main(String[] args) {

		int i= 10;
		int j= 22;
		int k=125;
System.out.println("Arthamatic Operations Generated by if_else condition");				
		int add= i+j+k;
		int diff= i-j;
		int dif= -k-j+k; 
		int mult = k*i;
		int div = (i+j)/k;
		float frac = j|k;

if(i>j)
{
		System.out.println("add=" + add);
}	else if(j>k)
{
	System.out.println("diff=" + diff);
}else if (i==j)
{
System.out.println("dif=" + dif);
}else if (j==k)
{
System.out.println("milt= " + mult);
}	else if (i==k)
{
System.out.println("div="+div);
}else 	
	System.out.println("am using the For Loop here");
for (i=15;i<=j; i++)
{
	System.out.println("fact="+frac);
}	 
		
		for(j=120;j<=k;j++)
		{
		System.out.println("am using the for loop condtion for 12 times inthi condion that's like 22-10=12");
			
			
		}
		
		}
	}
